import{a as B,S as M,i}from"./assets/vendor-CNqCr-V-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(t){if(t.ep)return;t.ep=!0;const a=e(t);fetch(t.href,a)}})();const S="53389210-1518ce0ab28dfc8ed2510f80a",y=15,P=B.create({baseURL:"https://pixabay.com/api/",timeout:1e4,params:{key:S,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:y}});async function b(o,s=1){if(!o||typeof o!="string")throw new Error("Query must be a non-empty string");try{return(await P.get("",{params:{q:o,page:s}})).data}catch(e){throw e}}const r={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")},q=new M(".gallery a",{captionsData:"alt",captionDelay:250});function L(o=[]){if(!r.gallery)return;const s=o.map(e=>`
    <div class="photo-card">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${e.likes}</span></p>
        <p class="info-item"><b>Views</b><span>${e.views}</span></p>
        <p class="info-item"><b>Comments</b><span>${e.comments}</span></p>
        <p class="info-item"><b>Downloads</b><span>${e.downloads}</span></p>
      </div>
    </div>`).join("");r.gallery.insertAdjacentHTML("beforeend",s),q.refresh()}function $(){r.gallery&&(r.gallery.innerHTML="")}function v(){r.loader&&r.loader.classList.remove("is-hidden")}function h(){r.loader&&r.loader.classList.add("is-hidden")}function f(){r.loadMoreBtn&&r.loadMoreBtn.classList.remove("is-hidden")}function p(){r.loadMoreBtn&&r.loadMoreBtn.classList.add("is-hidden")}const E=r;let m="",c=1,l=0;const d=document.querySelector("#form"),g=E.loadMoreBtn,D=E.gallery;p();h();d&&d.addEventListener("submit",async o=>{o.preventDefault();const e=(new FormData(d).get("searchQuery")||"").trim();if(!e){i.warning({title:"Warning",message:"Please enter a search query."});return}m=e,c=1,$(),p(),v(),await Promise.resolve();try{const n=await b(m,c);l=n.totalHits||0;const t=n.hits||[];if(l===0){i.error({title:"No results",message:"No images found. Try another query."});return}L(t),i.success({title:"Success",message:`Hooray! We found ${l} images.`}),c*y<l?f():i.info({title:"End",message:"We're sorry, but you've reached the end of search results."})}catch(n){console.error(n),i.error({title:"Error",message:"Something went wrong while fetching images."})}finally{h()}});g&&g.addEventListener("click",async()=>{v(),await Promise.resolve(),p(),c+=1;try{const s=(await b(m,c)).hits||[];if(s.length===0){i.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}L(s);const e=D.querySelector(".photo-card");if(e){const{height:n}=e.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}c*y<l?f():i.info({title:"End",message:"We're sorry, but you've reached the end of search results."})}catch(o){console.error(o),i.error({title:"Error",message:"Failed to load more images."}),c-=1,f()}finally{h()}});const Q=new URLSearchParams(window.location.search),w=Q.get("searchQuery");w&&(document.querySelector("#searchQuery").value=w,d.dispatchEvent(new Event("submit")));
//# sourceMappingURL=index.js.map
