import{a as M,S as B,i}from"./assets/vendor-CNqCr-V-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const h of a.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&n(h)}).observe(document,{childList:!0,subtree:!0});function e(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(t){if(t.ep)return;t.ep=!0;const a=e(t);fetch(t.href,a)}})();const S="53389210-1518ce0ab28dfc8ed2510f80a",p=15,q=M.create({baseURL:"https://pixabay.com/api/",timeout:1e4,params:{key:S,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:p}});async function w(r,s=1){if(!r||typeof r!="string")throw new Error("Query must be a non-empty string");try{return(await q.get("",{params:{q:r,page:s}})).data}catch(e){throw e}}const o={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")},P=new B(".gallery a",{captionsData:"alt",captionDelay:250});function L(r=[]){if(!o.gallery)return;const s=r.map(e=>`
    <div class="photo-card">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${e.likes}</span></p>
        <p class="info-item"><b>Views</b><span>${e.views}</span></p>
        <p class="info-item"><b>Comments</b><span>${e.comments}</span></p>
        <p class="info-item"><b>Downloads</b><span>${e.downloads}</span></p>
      </div>
    </div>`).join("");o.gallery.insertAdjacentHTML("beforeend",s),P.refresh()}function $(){o.gallery&&(o.gallery.innerHTML="")}function v(){o.loader&&o.loader.classList.remove("is-hidden")}function f(){o.loader&&o.loader.classList.add("is-hidden")}function y(){o.loadMoreBtn&&o.loadMoreBtn.classList.remove("is-hidden")}function d(){o.loadMoreBtn&&o.loadMoreBtn.classList.add("is-hidden")}const E=o;let m="",c=1,l=0;const u=document.querySelector("#search-form"),g=E.loadMoreBtn,D=E.gallery;d();f();u&&u.addEventListener("submit",async r=>{r.preventDefault();const e=(new FormData(u).get("searchQuery")||"").trim();if(!e){i.warning({title:"Warning",message:"Please enter a search query."});return}m=e,c=1,$(),d(),v();try{const n=await w(m,c);l=n.totalHits||0;const t=n.hits||[];if(l===0||t.length===0){i.error({title:"No results",message:"No images found. Try another query."}),f();return}L(t),i.success({title:"Success",message:`Hooray! We found ${l} images.`}),c*p<l?y():(d(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch(n){console.error(n),i.error({title:"Error",message:"Something went wrong while fetching images."})}finally{f()}});g&&g.addEventListener("click",async()=>{if(m){v(),d(),c+=1;try{const r=await w(m,c),s=r.hits||[];if(l=r.totalHits||l,s.length===0){i.info({title:"End",message:"We're sorry, but you've reached the end of search results."}),d();return}L(s);const e=D.querySelector(".photo-card");if(e){const{height:n}=e.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}c*p<l?y():(d(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.error(r),i.error({title:"Error",message:"Failed to load more images."}),c=Math.max(1,c-1),y()}finally{f()}}});const Q=new URLSearchParams(window.location.search),b=Q.get("searchQuery");b&&(u.searchQuery.value=b,u.dispatchEvent(new Event("submit")));
//# sourceMappingURL=index.js.map
